name = "tianai"
main = "worker.js"
compatibility_date = "2024-09-01"

# 绑定自定义域名
routes = [
  { pattern = "drvittoria.de5.net", custom_domain = true }
]


# Cloudflare KV 命名空间绑定：用于全球持久化存储文章与留言数据
[[kv_namespaces]]
binding = "BLOG_KV"
id = "6ef43971a8554502b81e24c10e077a25"

# Cloudflare Workers AI 绑定
[ai]
binding = "AI"

